version: '3.8'

services:
  app:
    container_name: whatsapp-gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      # Mount qr.html with consistent permissions (the container's file takes precedence)
      - ./qr.html:/app/qr.html:delegated
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - whatsapp-net

networks:
  whatsapp-net:
    driver: bridge